### ISSUE TITLE
Configuration property not detected by the Documenter

### ISSUE THREAD

**Issue by ecostanzi** [moduliths/moduliths#250]
I created a project using modulith tests (v 1.3.0) but the endpoint property hasn't been detected by the modulith `Documenter`. I cannot find the property and the related javadoc in the .adoc file.

The code and the tests are versioned here: https://github.com/ecostanzi/modulith-tests

The configuration class
```
@Configuration
@ConstructorBinding
@ConfigurationProperties(prefix = "configb")
public class ConfigB {

    /**
     * The endpoint to call
     */
    String endpoint;

    public String getEndpoint() {
        return endpoint;
    }

    public void setEndpoint(String endpoint) {
        this.endpoint = endpoint;
    }
}
```
In the generated asciidoc file the configuration class has been detected, but the endpoint property is missing.

```adoc
[%autowidth.stretch, cols="h,a"]
|===
|Base package
|`com.example.modulithtest.modules.moduleb`
|Spring components
|_Services_

* `c.e.m.m.m.ServiceB`

_Configuration properties_

* `c.e.m.m.m.ConfigB`
|Published events
|* `c.e.m.m.m.EventB` created by:
** `c.e.m.m.m.ServiceB.doSomething()`

|Properties
|none
|===
```

**Comment by odrotbohm** [comment]
The documentation generation is based on the `spring-boot-configuration-processor` artifact, documented in the Spring Boot [reference documentation](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#appendix.configuration-metadata.annotation-processor). This one needs to be present in your build to produce the metadata, extract Javadoc information etc.
